### ISSUE TITLE
b-tcvae encoder

### ISSUE THREAD

**Issue by rojinsafavi** [amir-abdi/disentanglement-pytorch#30]
Thanks Amir for providing this library.
I was looking at the original b-tcvae github code:
https://github.com/rtqichen/beta-tcvae

And I believe they did not map the encoding to mu and sigma layer, it seems that they only mapped it to mu. But in your code, it seems that you're following the VAE structure (mapping the input to mu and sigma layers). I was wondering if there is any specific reason for including/excluding the sigma layer?

Best,
Rojin

**Comment by amir-abdi** [comment]
Hmm... I checked their code and it seems that they also are encoding mu and sigma. See here (https://github.com/rtqichen/beta-tcvae/blob/master/vae_quant.py#L175):

    # define the guide (i.e. variational distribution) q(z|x)
    def encode(self, x):
        x = x.view(x.size(0), 1, 64, 64)
        # use the encoder to get the parameters used to define q(z|x)
        z_params = self.encoder.forward(x).view(x.size(0), self.z_dim, self.q_dist.nparams)
        # sample the latent code z
        zs = self.q_dist.sample(params=z_params)
        return zs, z_params

`q_dist` is set to `dist.Normal()` during initialization. So, it is a normal distribution, and encodes both mu and sigma.

**Comment by rojinsafavi** [comment]
Sorry, my bad! thanks for the clarification.

**Comment by amir-abdi** [comment]
Thank you for your comment. 
I did not have a code review partner, so, I appreciate any efforts to resolve any potential issues with my implementation. Thank you for your help.
