### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JohanYe** [amir-abdi/disentanglement-pytorch#49]
Thank you Amir for a great library.

You mentioned i could ask questions by raising them as issues. Do you know how much of the Google-Research disentanglement lab in tensorflow is implemented in your package? I prefer working in pytorch and was hoping to use your library as a substitute.

Thank you very much!

Br,
Johan Ye

**Comment by amir-abdi** [comment]
That is a good question.
Whiel https://github.com/google-research/disentanglement_lib has not gotten any new updates in the past 6 months; I have not really followed up on the details to check the consistency between the two libraries.

New disentanglement algorithms are emerging every now and then, but, unfortunately, neither mine or disentanglement_lib is keeping the source updated with the new trends.
